### ISSUE TITLE
DLL file not included

### ISSUE THREAD

**Issue by porygon21** [Kim-Lan/kar-autocounter#1]
Hey there, just a heads up, the `autocounter.dll` file generated in the `debug/bin` folder is not included in this repo, meaning someone has to build locally in order to generate it and throw it into livesplit. Not sure if that was intentional or not? 
Either way got it to build on my local machine, looks great!! Thanks for putting this together! Only other thing that might be user error on my part, the TextComponent defs for the PB variables are not assigned/defined anywhere, I assume they are Livesplit.core components but when I auto refactor them as such it has a problem with the settings field of it etc. So no biggie just removed them on my end in order to build.
Just wanted to throw the dll issue on your radar just in case you meant to include it.

**Comment by Kim-Lan** [comment]
Hello! The dll is under releases. Your input is much appreciated though. I have actually been working on an update to fix some things, including how I handle the text components. I am also updating the compatibility to (hopefully) be compatible with any of the newer versions of Dolphin.

If you want to check it out, here's the branch: https://github.com/Kim-Lan/kar-autocounter/tree/overhaul

Just a note, it _does not_ seem to be compatible with Dolphin 5.0 Stable anymore, but I have tested with a handful of the newer Dolphin beta and development builds.

**Comment by porygon21** [comment]
Oh snap, I'm a dummy 😂 my mistake! Yeah I'll take a look at the other branch here as well!
Huh interesting, I believe I'm using Doplhin 5.0, not sure if it's Stable or Beta though, I should probably investigate that 😂 . Either way, love this little tracker! It's dope!

**Comment by Kim-Lan** [comment]
I'm glad you're enjoying the tracker! I saw you hopped into camkatsu's discord, so feel free to message in the gaming channel there or DM me about issues, if you'd like!
